// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/serroba/features/internal/handler (interfaces: FlagService)
//
// Generated by this command:
//
//	mockgen -destination=mock_service_test.go -package=handler_test . FlagService
//

// Package handler_test is a generated GoMock package.
package handler_test

import (
	context "context"
	reflect "reflect"

	flags "github.com/serroba/features/internal/flags"
	gomock "go.uber.org/mock/gomock"
)

// MockFlagService is a mock of FlagService interface.
type MockFlagService struct {
	ctrl     *gomock.Controller
	recorder *MockFlagServiceMockRecorder
	isgomock struct{}
}

// MockFlagServiceMockRecorder is the mock recorder for MockFlagService.
type MockFlagServiceMockRecorder struct {
	mock *MockFlagService
}

// NewMockFlagService creates a new mock instance.
func NewMockFlagService(ctrl *gomock.Controller) *MockFlagService {
	mock := &MockFlagService{ctrl: ctrl}
	mock.recorder = &MockFlagServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlagService) EXPECT() *MockFlagServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFlagService) Create(ctx context.Context, flag flags.Flag) (flags.Flag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, flag)
	ret0, _ := ret[0].(flags.Flag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFlagServiceMockRecorder) Create(ctx, flag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFlagService)(nil).Create), ctx, flag)
}

// Evaluate mocks base method.
func (m *MockFlagService) Evaluate(ctx context.Context, key flags.FlagKey, evalCtx flags.EvalContext) (flags.EvalResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ctx, key, evalCtx)
	ret0, _ := ret[0].(flags.EvalResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockFlagServiceMockRecorder) Evaluate(ctx, key, evalCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockFlagService)(nil).Evaluate), ctx, key, evalCtx)
}
